es:
  host: elasticsearch.srv.webis.de
  port: 9200
  username: null
  password: null
es_index_serps:
  name: aql_serps
  settings:
    number_of_shards: 10
    number_of_replicas: 2
  mapping: {} # TODO
es_index_results:
  name: aql_results
  settings:
    number_of_shards: 20
    number_of_replicas: 2
  mapping: {} # TODO
es_index_url_query_parsers:
  name: aql_url_query_parsers
  settings:
    number_of_shards: 1
    number_of_replicas: 2
  mapping:
    properties:
      url_filter_regex:
        type: keyword
      parser_type:
        type: keyword
      parameter:
        type: keyword
      segment:
        type: integer
      replacements:
        type: object
        properties:
          search:
            type: keyword
          replace:
            type: keyword
es_index_url_page_parsers:
  name: aql_url_page_parsers
  settings:
    number_of_shards: 1
    number_of_replicas: 2
  mapping:
    properties:
      url_filter_regex:
        type: keyword
      parser_type:
        type: keyword
      parameter:
        type: keyword
      segment:
        type: integer
      replacements:
        type: object
        properties:
          search:
            type: keyword
          replace:
            type: keyword
es_index_url_offset_parsers:
  name: aql_url_offset_parsers
  settings:
    number_of_shards: 1
    number_of_replicas: 2
  mapping:
    properties:
      url_filter_regex:
        type: keyword
      parser_type:
        type: keyword
      parameter:
        type: keyword
      segment:
        type: integer
      replacements:
        type: object
        properties:
          search:
            type: keyword
          replace:
            type: keyword
es_index_url_language_parsers:
  name: aql_url_language_parsers
  settings:
    number_of_shards: 1
    number_of_replicas: 2
  mapping:
    properties:
      url_filter_regex:
        type: keyword
      parser_type:
        type: keyword
      parameter:
        type: keyword
      segment:
        type: integer
      replacements:
        type: object
        properties:
          search:
            type: keyword
          replace:
            type: keyword
es_index_serp_query_parsers:
  name: aql_serp_query_parsers
  settings:
    number_of_shards: 1
    number_of_replicas: 2
  mapping:
    properties:
      url_filter_regex:
        type: keyword
      parser_type:
        type: keyword
      html_selector:
        type: keyword
      html_attribute:
        type: keyword
      html_text:
        type: boolean
      replacements:
        type: object
        properties:
          search:
            type: keyword
          replace:
            type: keyword
es_index_serp_snippets_parsers:
  name: aql_serp_snippets_parsers
  settings:
    number_of_shards: 1
    number_of_replicas: 2
  mapping:
    properties:
      url_filter_regex:
        type: keyword
      parser_type:
        type: keyword
      html_selector:
        type: keyword
      html_selector_url:
        type: keyword
      html_attribute_url:
        type: keyword
      html_selector_title:
        type: keyword
      html_selector_text:
        type: keyword
es_index_serp_direct_answer_parsers:
  name:  aql_serp_direct_answer_parsers
  settings:
    number_of_shards: 1
    number_of_replicas: 2
  mapping:
    properties:
      url_filter_regex:
        type: keyword
      parser_type:
        type: keyword
      html_selector:
        type: keyword
