#!/bin/bash -e

srun \
  --cpus-per-task 4 \
  --ntasks-per-node 1 \
  --mem 40G \
  --container-writable \
  --container-image python:3.10 \
  --container-name web-archive-query-log-python-3.10 \
  --container-mounts "$PWD":/workspace \
  --chdir "$PWD" \
  --pty \
  sh -c "
  cd /workspace
  python -m pipenv run python -m web_archive_query_log $*
  "
