#!/bin/bash -e

srun \
  --cpus-per-task 1 \
  --mem=4G \
  --container-writable \
  --container-image=python:3.10 \
  --container-name=web-archive-query-log-python-3.10 \
  --container-mounts="$PWD":/workspace \
  --chdir "$PWD" \
  --pty \
  sh -c "
  cd /workspace
  pip install --upgrade pip cython pipenv
  python -m pipenv install --deploy
  "
