#!/bin/bash -e

srun \
  --cpus-per-task 1 \
  --mem=4G \
  --container-writable \
  --container-image=python:3.10 \
  --container-name=web-archive-query-log-python-3.10 \
  --container-mounts="$PWD":/workspace \
  --chdir "$PWD" \
  --pty \
  su -c "
  pipenv run python -m web_archive_query_log
  "
