apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-api
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: {{ $.Values.api.ingressClassName }}
  rules:
    - host: {{ $.Values.api.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-api
                port:
                  name: http
  tls:
    - secretName: cert-webis-de
      hosts:
        - {{ $.Values.api.host }}
