apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-config-map
  namespace: {{ $.Release.Namespace }}
data:
  config.yml: |
    es:
      host: {{ $.Values.elasticsearch.host }}
      port: {{ $.Values.elasticsearch.port }}
    s3:
      endpoint_url: {{ $.Values.s3.endpoint_url }}
      bucket_name: {{ $.Values.s3.bucket_name }}
