apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $.Release.Name }}-serps-parse-url-page
  namespace: {{ $.Release.Namespace }}
  annotations:
    checksum/secret: {{ include (print $.Template.BasePath "/archive-query-log-secret.yaml") . | sha256sum }}
spec:
  suspend: {{ not $.Values.serpsParseUrlPage.enabled }}
  schedule: {{ $.Values.serpsParseUrlPage.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      completions: {{ $.Values.serpsParseUrlPage.completions }}
      parallelism: {{ $.Values.serpsParseUrlPage.parallelism }}
      backoffLimit: {{ $.Values.serpsParseUrlPage.backoffLimit }}
      ttlSecondsAfterFinished: {{ mul 60 $.Values.serpsParseUrlPage.ttlMinutesAfterFinished }}
      template:
        spec:
          containers:
            - name: {{ $.Release.Name }}-serps-parse-url-page
              image: "{{ .Values.image }}:{{ .Chart.AppVersion }}"
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  memory: 4Gi
              command:
                - /venv/bin/python
                - -m
                - archive_query_log
                - serps
                - parse
                - url-page
              env:
                - name: ELASTICSEARCH_HOST
                  value: {{ $.Values.elasticsearch.host | quote }}
                - name: ELASTICSEARCH_PORT
                  value: {{ $.Values.elasticsearch.port | quote }}
                - name: ELASTICSEARCH_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ $.Release.Name }}-secret
                      key: elasticsearchUsername
                - name: ELASTICSEARCH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ $.Release.Name }}-secret
                      key: elasticsearchPassword
                - name: ELASTICSEARCH_INDEX_ARCHIVES
                  value: {{ $.Values.elasticsearch.indexArchives | quote }}
                - name: ELASTICSEARCH_INDEX_PROVIDERS
                  value: {{ $.Values.elasticsearch.indexProviders | quote }}
                - name: ELASTICSEARCH_INDEX_SOURCES
                  value: {{ $.Values.elasticsearch.indexSources | quote }}
                - name: ELASTICSEARCH_INDEX_CAPTURES
                  value: {{ $.Values.elasticsearch.indexCaptures | quote }}
                - name: ELASTICSEARCH_INDEX_SERPS
                  value: {{ $.Values.elasticsearch.indexSerps | quote }}
                - name: ELASTICSEARCH_INDEX_RESULTS
                  value: {{ $.Values.elasticsearch.indexResults | quote }}
                - name: ELASTICSEARCH_INDEX_URL_QUERY_PARSERS
                  value: {{ $.Values.elasticsearch.indexUrlQueryParsers | quote }}
                - name: ELASTICSEARCH_INDEX_URL_PAGE_PARSERS
                  value: {{ $.Values.elasticsearch.indexUrlPageParsers | quote }}
                - name: ELASTICSEARCH_INDEX_URL_OFFSET_PARSERS
                  value: {{ $.Values.elasticsearch.indexUrlOffsetParsers | quote }}
                - name: ELASTICSEARCH_INDEX_WARC_QUERY_PARSERS
                  value: {{ $.Values.elasticsearch.indexWarcQueryParsers | quote }}
                - name: ELASTICSEARCH_INDEX_WARC_SNIPPETS_PARSERS
                  value: {{ $.Values.elasticsearch.indexWarcSnippetsParsers | quote }}
                - name: ELASTICSEARCH_INDEX_WARC_DIRECT_ANSWERS_PARSERS
                  value: {{ $.Values.elasticsearch.indexWarcDirectAnswersParser | quote }}
                - name: ELASTICSEARCH_INDEX_WARC_MAIN_CONTENT_PARSERS
                  value: {{ $.Values.elasticsearch.indexWarcMainContentParser | quote }}
                - name: S3_ENDPOINT_URL
                  value: {{ $.Values.s3.endpointUrl | quote }}
                - name: S3_BUCKET_NAME
                  value: {{ $.Values.s3.bucketName | quote }}
                - name: S3_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ $.Release.Name }}-secret
                      key: s3AccessKey
                - name: S3_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ $.Release.Name }}-secret
                      key: s3SecretKey
                - name: WARC_CACHE_PATH_SERPS
                  value: {{ $.Values.warcCache.pathSerps | quote }}
              volumeMounts:
                - name: {{ $.Release.Name }}-warc-cache-path-serps
                  mountPath: {{ $.Values.warcCache.pathSerps }}
          restartPolicy: OnFailure
          volumes:
            - name: {{ $.Release.Name }}-warc-cache-path-serps
              hostPath:
                path: {{ $.Values.warcCache.pathSerps }}
                type: DirectoryOrCreate
