apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-secret
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  elasticsearchUsername: {{ $.Values.elasticsearch.username | b64enc | quote }}
  elasticsearchPassword: {{ $.Values.elasticsearch.password | b64enc | quote }}
  s3AccessKey: {{ $.Values.s3.accessKey | b64enc | quote }}
  s3SecretKey: {{ $.Values.s3.secretKey | b64enc | quote }}
