from archive_query_log.namespaces import (
    NAMESPACE_SOURCE,
    NAMESPACE_CAPTURE,
    NAMESPACE_SERP,
    NAMESPACE_WEB_SEARCH_RESULT_BLOCK,
    NAMESPACE_SPECIAL_CONTENTS_RESULT_BLOCK,
    NAMESPACE_URL_QUERY_PARSER,
    NAMESPACE_URL_PAGE_PARSER,
    NAMESPACE_URL_OFFSET_PARSER,
    NAMESPACE_URL_LANGUAGE_PARSER,
    NAMESPACE_WARC_QUERY_PARSER,
    NAMESPACE_WARC_WEB_SEARCH_RESULT_BLOCKS_PARSER,
    NAMESPACE_WARC_SPECIAL_CONTENTS_RESULT_BLOCKS_PARSER,
    NAMESPACE_WARC_MAIN_CONTENT_PARSER,
    NAMESPACE_WARC_DOWNLOADER,
)


def test_namespaces_different() -> None:
    all_parsers = (
        NAMESPACE_SOURCE,
        NAMESPACE_CAPTURE,
        NAMESPACE_SERP,
        NAMESPACE_WEB_SEARCH_RESULT_BLOCK,
        NAMESPACE_SPECIAL_CONTENTS_RESULT_BLOCK,
        NAMESPACE_URL_QUERY_PARSER,
        NAMESPACE_URL_PAGE_PARSER,
        NAMESPACE_URL_OFFSET_PARSER,
        NAMESPACE_URL_LANGUAGE_PARSER,
        NAMESPACE_WARC_QUERY_PARSER,
        NAMESPACE_WARC_WEB_SEARCH_RESULT_BLOCKS_PARSER,
        NAMESPACE_WARC_SPECIAL_CONTENTS_RESULT_BLOCKS_PARSER,
        NAMESPACE_WARC_MAIN_CONTENT_PARSER,
        NAMESPACE_WARC_DOWNLOADER,
    )
    assert len(all_parsers) == len(set(all_parsers))
