name: CI

on:
  push:

jobs:
  python-build:
    name: 🏗️ Build Python wheels
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v6
      - name: 🧰 Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: 🧰 Install dependencies
        run: pip install build twine
      - name: 🏗️ Build Python wheels
        run: python -m build
      - name: 🧪 Check package bundles
        run: twine check dist/*
      - name: 📤 Upload Python wheels
        uses: actions/upload-artifact@v7
        with:
          name: wheels
          path: dist
  python-code-check:
    name: 🔍 Check Python code
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v6
      - name: 🧰 Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: 🧰 Install dependencies
        run: pip install .[tests]
      - name: 🔍 Check Python code
        run: ruff check .
  python-typing:
    name: 🔍 Check Python static typing
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v6
      - name: 🧰 Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: 🧰 Install dependencies
        run: pip install .[tests]
      - name: 🔍 Check Python static typing
        run: mypy .
  python-test:
    name: 🧪 Test Python code
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v6
      - name: 🧰 Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: 🧰 Install dependencies
        run: pip install .[tests]
      - name: 🧪 Test Python code
        run: pytest --cov --cov-report=xml .
      - name: 📤 Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  node-build-browser:
    name: 🏗️ Build browser Node app
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v6
      - name: 🧰 Install Node
        uses: actions/setup-node@v6
        with:
          node-version: "24.13"
          check-latest: true
          cache-dependency-path: browser/package-lock.json
      - name: 🧰 Install Node dependencies
        working-directory: browser/
        run: npm clean-install
      - name: 🏗️ Build browser Node app
        working-directory: browser/
        run: npm run build
      - name: 📤 Upload app for GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: browser/dist/aql-frontend/browser/
  node-check-browser:
    name: 🔍 Check browser Node app code
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v6
      - name: 🧰 Install Node
        uses: actions/setup-node@v6
        with:
          node-version: "24.13"
          check-latest: true
          cache-dependency-path: browser/package-lock.json
      - name: 🧰 Install Node dependencies
        working-directory: browser/
        run: npm clean-install
      - name: 🔍 Check Node app code
        working-directory: browser/
        run: npm run lint
  node-security-browser:
    name: 🔍 Check browser Node app security
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v6
      - name: 🧰 Install Node
        uses: actions/setup-node@v6
        with:
          node-version: "24.13"
          cache-dependency-path: browser/package-lock.json
      - name: 🧰 Install Node dependencies
        working-directory: browser/
        run: npm clean-install
      - name: 🔍 Check Node app security
        working-directory: browser/
        run: npm audit --audit-level critical
  node-test-browser:
    name: 🧪 Test browser Node app
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v6
      - name: 🧰 Install Node
        uses: actions/setup-node@v6
        with:
          node-version: "24.13"
          cache-dependency-path: browser/package-lock.json
      - name: 🧰 Install Chrome browser
        uses: browser-actions/setup-chrome@v2
      - name: 🧰 Install Node dependencies
        working-directory: browser/
        run: npm clean-install
      - name: 🧪 Test Node app
        working-directory: browser/
        run: npm run test:ci
      - name: 📤 Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: browser/coverage/
  docker-build:
    name: 🏗️ Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v6
      - name: 🧰 Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: 🧰 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 🏗️ Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
  docker-build-browser:
    name: 🏗️ Build browser Docker image
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v6
      - name: 🧰 Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: 🧰 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 🏗️ Build browser Docker image
        uses: docker/build-push-action@v7
        with:
          context: browser/
          push: false
  helm-package:
    name: 🏗️ Package Helm chart
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v6
        with:
          fetch-tags: true
      - name: 🧰 Install Helm
        uses: azure/setup-helm@v5.0.0
      - name: ℹ️ Determine version
        id: version
        uses: release-kit/semver@v2
        with:
          source: latest-tag
      - name: 🏗️ Package Helm chart
        run: helm package helm/ --version ${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}
      - name: 📤 Upload Helm chart
        uses: actions/upload-artifact@v7
        with:
          name: helm-chart
          path: archive-query-log-*.tgz
  python-publish:
    name: 🚀 Publish Python wheels
    if: github.event_name == 'push' && endsWith(github.event.base_ref, 'main') && startsWith(github.ref, 'refs/tags')
    needs:
      - python-build
      - python-code-check
      - python-typing
      - python-test
      - docker-build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v6
      - name: 📥 Download Python wheels
        uses: actions/download-artifact@v8
        with:
          name: wheels
          path: dist
      - name: 🚀 Publish Python wheels
        uses: pypa/gh-action-pypi-publish@release/v1
  docker-publish:
    name: 🚀 Publish Docker image
    if: github.event_name == 'push' && endsWith(github.event.base_ref, 'main') && startsWith(github.ref, 'refs/tags')
    permissions:
      packages: write
    needs:
      - python-build
      - python-code-check
      - python-typing
      - python-test
      - docker-build
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v6
      - name: 🧰 Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: 🧰 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 🔑 Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: ℹ️ Extract image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
      - name: 🚀 Build and push image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  docker-publish-browser:
    name: 🚀 Publish browser Docker image
    if: github.event_name == 'push' && endsWith(github.event.base_ref, 'main') && startsWith(github.ref, 'refs/tags')
    permissions:
      packages: write
    needs:
      - node-build-browser
      - node-check-browser
      - node-security-browser
      - node-test-browser
      - docker-build-browser
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v6
      - name: 🧰 Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: 🧰 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 🔑 Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: ℹ️ Extract image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/browser
      - name: 🚀 Build and push image
        uses: docker/build-push-action@v7
        with:
          context: browser/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  helm-publish:
    name: 🚀 Publish Helm chart
    if: github.event_name == 'push' && endsWith(github.event.base_ref, 'main') && startsWith(github.ref, 'refs/tags')
    needs:
      - helm-package
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v6
      - name: 📥 Download Helm chart
        uses: actions/download-artifact@v8
        with:
          name: helm-chart
          path: .
      - name: 🔑 Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 🚀 Publish Helm chart
        run: helm push archive-query-log-*.tgz oci://ghcr.io/${{ github.repository }}/charts
  github-release:
    name: 🚀 Create GitHub release
    if: github.event_name == 'push' && endsWith(github.event.base_ref, 'main') && startsWith(github.ref, 'refs/tags')
    needs:
      - python-build
      - python-code-check
      - python-typing
      - python-test
      - python-publish
      - docker-build
      - docker-publish
      - node-build-browser
      - node-check-browser
      - node-security-browser
      - node-test-browser
      - docker-build-browser
      - docker-publish-browser
      - helm-package
      - helm-publish
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check-out
        uses: actions/checkout@v6
      - name: 📥 Download Python wheels
        uses: actions/download-artifact@v8
        with:
          name: wheels
          path: dist
      - name: 🚀 Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: dist/*
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
          generate_release_notes: true
